app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/ui/components/comment/CommentRoutines.kt, app/src/main/java/com/jerboa/ui/components/post/PostActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostViewModel.kt
=> Comment tree rework 1

app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt, app/src/main/java/com/jerboa/ui/components/home/HomeViewModel.kt
=> fix signout

app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityActivity.kt
=> add fab for create post from community page

app/build.gradle, app/src/main/java/com/jerboa/ui/components/common/AppBars.kt, app/src/main/java/com/jerboa/ui/components/common/VoteHelpers.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityLink.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileLink.kt, app/src/main/java/com/jerboa/ui/components/post/PostListing.kt, build.gradle, gradle/wrapper/gradle-wrapper.properties
- Fixes #327
- Fixes #326
- Fixes #325
=> Use muted profile names, better colors, and align post header bar.

app/src/main/java/com/jerboa/db/AppDB.kt
=> Revert "Making font size 16 by default. Fixes #330"

app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt, app/src/main/java/com/jerboa/ui/components/post/PostActivity.kt, app/src/main/java/com/jerboa/ui/theme/Sizes.kt
=> Making icons larger, adding node keys

app/src/main/AndroidManifest.xml, app/src/main/java/com/jerboa/ui/components/comment/edit/CommentEdit.kt, app/src/main/java/com/jerboa/ui/components/comment/reply/CommentReplyActivity.kt, app/src/main/java/com/jerboa/ui/components/community/list/CommunityListActivity.kt, app/src/main/java/com/jerboa/ui/components/login/Login.kt, app/src/main/java/com/jerboa/ui/components/login/LoginActivity.kt, app/src/main/java/com/jerboa/ui/components/post/create/CreatePost.kt, app/src/main/java/com/jerboa/ui/components/post/edit/PostEdit.kt, app/src/main/java/com/jerboa/ui/components/post/edit/PostEditActivity.kt, app/src/main/java/com/jerboa/ui/components/privatemessage/PrivateMessageReplyActivity.kt, app/src/main/java/com/jerboa/ui/components/report/CreateReport.kt, app/src/main/java/com/jerboa/ui/components/settings/account/AccountSettings.kt
=> Fixing IME padding issues. Fixes #350

app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/ui/theme/Color.kt, app/src/main/java/com/jerboa/ui/theme/Theme.kt
Added Blue theme color. Screenshots compared to Pink for reference:
=> Added Blue theme color

app/build.gradle, app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/db/AppDB.kt, app/src/main/java/com/jerboa/ui/components/common/MarkdownHelper.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityActivity.kt, app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostActivity.kt, app/src/main/java/com/jerboa/ui/components/settings/about/AboutActivity.kt, app/src/main/java/com/jerboa/ui/components/settings/lookandfeel/LookAndFeelActivity.kt, app/src/main/res/values/strings.xml
Fixes #396 
Consider blocking on #447 for strings
=> Add custom tab support

app/src/main/java/com/jerboa/ui/components/home/Home.kt, app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt
Closes account switcher when drawer is closed
=> Close account switcher when drawer is closed

app/src/main/java/com/jerboa/ui/components/settings/lookandfeel/LookAndFeelActivity.kt
This was a mistake from when I rebased #474.
=> Fix show voting arrows in list view option not updating

app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt
=> Remove check to allow replying to own comments

app/src/main/java/com/jerboa/ui/components/settings/account/AccountSettings.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values/strings.xml
=> Fix the missing 'Old' default sort account setting.

app/src/main/AndroidManifest.xml
Alphabetized the list of instances and added the following new instances to intent list, to match PR #505: 
lemmy.ca
lemmy.one
lemmy.world
midwest.social
sh.itjust.works
I can investigate creating automation around updating DEFAULT_LEMMY_INSTANCES and AndroidManifest.xml based on defined criteria and information from https://the-federation.info/platform/73, if the maintainers would be interested in adopting that approach.
=> Update AndroidManifest.xml to match instances added in #505

app/src/main/java/com/jerboa/ui/components/common/PictrsImage.kt
I've increased the blur from 20 to 100.
This way it is harder to see what is behind the blur and thus hides the NSFW posts more effectively.
Fixes this issue: https://github.com/dessalines/jerboa/issues/571
=> Increased NSFW blur

app/src/main/AndroidManifest.xml, app/src/main/res/xml/locales_config.xml
Also fixing deprecated permission.
=> Support android 13's per-app language selection, fixes #603

app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/db/AppDB.kt, app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt, app/src/main/java/com/jerboa/ui/components/common/MarkdownHelper.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityActivity.kt, app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostActivity.kt, app/src/main/java/com/jerboa/ui/components/settings/about/AboutActivity.kt, app/src/main/java/com/jerboa/ui/components/settings/lookandfeel/LookAndFeelActivity.kt, app/src/main/res/values/strings.xml
This only works in chrome for now as I can't find any documentation for which other browsers support this feature or how to enable it. Fixes #599
=> Add option to use private custom tabs when available

app/build.gradle, app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityActivity.kt, app/src/main/java/com/jerboa/ui/components/inbox/InboxActivity.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostListings.kt
~I have not fully tested this yet~
=> Fix accompanist deprecations

app/src/main/java/com/jerboa/MainActivity.kt
Fixes #525. Looks like a simple typo.
=> Show action bar by default

app/build.gradle, app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt, app/src/main/java/com/jerboa/ui/components/common/MarkdownHelper.kt, app/src/main/java/com/jerboa/ui/components/settings/about/AboutActivity.kt, app/src/test/java/com/jerboa/ui/components/common/LemmyLinkPluginTest.kt
=> Open lemmy-verse links in Jerboa

app/src/main/AndroidManifest.xml
Closes #559 
Using the solution provided in this [StackOverflow answer](https://stackoverflow.com/a/32283912) to preserve state across screen orientation & size changes.
=> Preserving state on orientation change.

.github/ISSUE_TEMPLATE/bug_report.md
Update bug_report.md to include logs when the app crashes
=> Update bug_report.md to include logs

app/src/main/java/com/jerboa/api/Http.kt, app/src/main/java/com/jerboa/ui/components/inbox/InboxViewModel.kt
Small fix for marking inbox replies as read.
=> Fix crash when marking comment as read

app/src/main/java/com/jerboa/ui/components/home/Home.kt
=> App settings should be visible if the user is not logged in

app/src/main/res/values-fr/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-nl/strings.xml
Following up on https://github.com/dessalines/jerboa/pull/699
=> Remove remaining voteToggle unused translations

app/src/main/java/com/jerboa/api/Http.kt, app/src/main/java/com/jerboa/util/DisableLog.kt
Just followed a stackoverflow suggestion, this should solve the logcat issue closing #783
=> Fix passwords in plaintext on logcat

app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/api/Http.kt, app/src/main/res/values/strings.xml
Possible fix for #859.
Fixes #831.
=> Catch network errors and show a toast

app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt
=> Include taglines with the scrollable post view

app/build.gradle.kts, benchmarks/build.gradle.kts
=> Bump dependencies

app/src/main/java/com/jerboa/ui/components/post/PostActivity.kt
Fixes #891 
https://github.com/dessalines/jerboa/assets/67873169/4e6997de-b9ad-4e5e-98a5-f775633ae941
=> Fix downvote on post in postview doing a upvote

app/src/main/res/values-ko/strings.xml
=> Remove `app_name` from strings.xml for `ko`

app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt
=> When drawer is open, close it if back is pressed.

app/src/main/res/values-fr/strings.xml
Just small FR typos corrections
=> Fix some FR translation typos

app/src/main/java/com/jerboa/ui/components/home/Home.kt
=> Show main sidebar content even when account switcher is shown

app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/model/AccountSettingsViewModel.kt, app/src/main/java/com/jerboa/model/CommentReplyViewModel.kt, app/src/main/java/com/jerboa/model/PostViewModel.kt, app/src/main/java/com/jerboa/ui/components/comment/reply/CommentReplyActivity.kt, app/src/main/java/com/jerboa/ui/components/common/Navigation.kt, app/src/main/java/com/jerboa/ui/components/inbox/InboxActivity.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostActivity.kt, app/src/main/java/com/jerboa/ui/components/settings/account/AccountSettings.kt, app/src/main/java/com/jerboa/ui/components/settings/account/AccountSettingsActivity.kt
This should have been part of #994
=> Move more viewmodels into com.jerboa.model package

app/src/main/java/com/jerboa/ui/components/person/PersonProfileLink.kt, app/src/main/res/values/strings.xml
=> Indicate persons that are bots

app/src/main/java/com/jerboa/ui/components/common/MarkdownHelper.kt
I tested this build for a half hour and I could not reproduce the issue any more. So believe this fixes it. 
Fixes #1021
=> Revert #767 should fix post opens the wrong one sometimes

app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityActivity.kt, app/src/main/java/com/jerboa/ui/components/post/create/CreatePostActivity.kt
Half the code for this was already there. I think nawtheeh forgot to finish it.
=> Auto fill in community name for posts created in community

app/src/main/java/com/jerboa/ui/components/imageviewer/ImageViewerActivity.kt
=> Fix image viewer adding unneeded padding on android 10 and below

app/src/main/java/com/jerboa/api/Http.kt
By default it is 10s, this changes it to 30s
Fixes #1070
=> Increase timeout of connections to 30s

app/src/main/java/com/jerboa/model/HomeViewModel.kt, app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt
=> Retain scroll position of feed after swapping navigation

app/src/main/res/values-ko/strings.xml
=> Update strings.xml for `ko`

app/src/main/java/com/jerboa/ui/components/comment/CommentNodes.kt, app/src/main/java/com/jerboa/ui/components/post/PostActivity.kt
This allows users to scroll a bit past the end of comment lists. I personally like this and its what Boost does.
=> Add spacer to bottom of comment lists

app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfile.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileActivity.kt
https://github.com/dessalines/jerboa/assets/67873169/af58d38a-35d6-4698-80b9-8e56a3a141c3
Fix #1081
=> Fix menubar icon when viewing someones profile

app/src/main/java/com/jerboa/ui/components/community/CommunityActivity.kt, app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostListing.kt, app/src/main/java/com/jerboa/ui/components/post/PostListings.kt
Also removed the default value because I shot myself in the foot with it
=> Don't show posts as read in saved and profile views

app/src/main/java/com/jerboa/ui/components/home/BottomNavActivity.kt
As requested by #1080 . Also provides [a gesture to refresh the feed](https://lemmy.ml/post/2378218).
=>  Scroll to top if homepage button pressed when on the home... (#1080)

app/src/main/java/com/jerboa/model/PostViewModel.kt, app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt, app/src/main/res/values/strings.xml
=> Properly fix read more replies bug introduced in lemmy 18.3

app/src/main/java/com/jerboa/ui/components/settings/account/AccountSettings.kt, app/src/main/java/com/jerboa/ui/components/settings/account/AccountSettingsActivity.kt, app/src/main/res/values/strings.xml
It correctly opens my authenticator app and creates a account
https://github.com/dessalines/jerboa/assets/67873169/27ee92a3-39a5-4b5f-b010-4ab70db80b7d
Fixes #1136
=> Add 2FA user setting

.woodpecker.yml
pipeline now changes to steps in V1, also updated to the latest image
=> Update woodpecker config

.woodpecker.yml
A few woodpecker env vars have changed.
=> Fixing woodpecker env vars.

app/src/main/java/com/jerboa/ui/components/common/Dialogs.kt, app/src/main/java/com/jerboa/ui/components/common/DropdownMenu.kt, app/src/main/java/com/jerboa/ui/components/inbox/Inbox.kt
=> Use M3 menu dropdown for inbox unread sort

app/src/main/java/com/jerboa/ui/components/community/Community.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityActivity.kt
Addresses #663 
https://github.com/dessalines/jerboa/assets/42601911/5dceda69-330e-4d68-ada4-11a041c180c9
=> Allow post mode change in Community

app/src/main/java/com/jerboa/ui/components/imageviewer/ImageViewerActivity.kt
The default zoom is pretty limited. This small change allows a greater zoom capabliity
=> Increase the zoom capability of the imageviewer

app/src/main/java/com/jerboa/JerboaAppState.kt, app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/feat/UserActions.kt, app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt, app/src/main/java/com/jerboa/ui/components/comment/mentionnode/CommentMentionNode.kt, app/src/main/java/com/jerboa/ui/components/comment/replynode/CommentReplyNode.kt, app/src/main/java/com/jerboa/ui/components/common/DropdownMenu.kt, app/src/main/java/com/jerboa/ui/components/common/InputFields.kt, app/src/main/java/com/jerboa/ui/components/common/LinkDropDownMenu.kt, app/src/main/java/com/jerboa/ui/components/common/MarkdownHelper.kt, app/src/main/java/com/jerboa/ui/components/common/PictrsImage.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityActivity.kt, app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt, app/src/main/java/com/jerboa/ui/components/imageviewer/ImageViewerActivity.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostListing.kt, app/src/main/java/com/jerboa/ui/components/post/PostListings.kt, app/src/main/java/com/jerboa/util/markwon/BetterLinkMovementMethod.kt, app/src/main/java/com/jerboa/util/markwon/ClickableCoilImagesPlugin.kt, app/src/main/res/values/betterlinkmovementmethod.xml, app/src/main/res/values/strings.xml
https://github.com/dessalines/jerboa/assets/67873169/aadac127-7aae-4cfd-9db1-5370d5399bca
Fixes #1096
Fixes #516 by using a better link movementmethod
Fixes #829
=> Add long click link popup menu, including actions

app/src/main/java/com/jerboa/ui/components/drawer/DrawerActivity.kt
=> Sort drawer subscriptions on title instead

app/build.gradle.kts, settings.gradle.kts
This issue has been reported and fixed
Fixes #1212
=> Fix wrong aligment sometimes for images in ImageViewer with RTL

app/src/main/java/com/jerboa/Utils.kt
=> Fix link not opening in Chrome If private tabs setting is on without CustomTab being on

app/build.gradle.kts, app/src/main/java/com/jerboa/ui/components/imageviewer/ImageViewerActivity.kt
Reverts dessalines/jerboa#1237
=> Revert "Fix zooming difficulties" and temporary remove Swipe to exit in ImageViewer

app/src/main/java/com/jerboa/ui/components/settings/crashlogs/CrashLogsActivity.kt
=> Sort crash logs by new, and display elapsed time

app/src/main/java/com/jerboa/ui/components/post/PostActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostListing.kt
Also moved its location a bit, UI wise looks a bit better now
Fixes #1248 
https://github.com/dessalines/jerboa/assets/67873169/8d36bdcd-b676-475c-bd9f-554931dd43dd
=> Fix post delete not working from within PostActivity

app/build.gradle.kts, app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/feat/AccountVerificationState.kt, app/src/main/java/com/jerboa/ui/components/community/Community.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfile.kt, benchmarks/build.gradle.kts, build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
Also upgrades AGP, and some deps.
=> Upgrading gradle to 8.3

app/src/main/java/com/jerboa/feat/AccountVerificationState.kt
The crash is because the verification tried to make API instance for the Anon account. Which causes a crash as it gives a empty string and thus then tries to do a version call to to localhost. 
I will comeback to this later. This decent fix, but there is another edge case to consider.
Technically its possible that the account will reference a url to a instance that isn't valid anymore. (Shutdown instance). And then we will have the same problem.
=> Fix crash on opening profile anonymous

app/build.gradle.kts, app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/ui/components/post/create/CreatePostActivity.kt, app/src/test/java/com/jerboa/UtilsKtTest.kt, settings.gradle.kts
Fix empty url causing post creation failing
Also fixed logging. httpClient should start logging now in logcat. (Once you pull the new release in)
=> Fix empty url causing post creation failing

app/build.gradle.kts
=> Fix image upload

app/src/main/java/com/jerboa/model/CommunityViewModel.kt, app/src/main/java/com/jerboa/model/HomeViewModel.kt, app/src/main/java/com/jerboa/model/PostsViewModel.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityActivity.kt
=> Fix initial default sort in community not being used

app/src/main/java/com/jerboa/model/CommunityViewModel.kt
=> Fix loading more posts in community view for 0.18 instances

app/src/main/java/com/jerboa/ui/components/common/AppBars.kt
=> Making botton app bar smaller when descriptions are hidden.

app/src/main/java/com/jerboa/ui/components/settings/SettingsActivity.kt, app/src/main/java/com/jerboa/ui/components/settings/about/AboutActivity.kt, app/src/main/java/com/jerboa/ui/components/settings/account/AccountSettings.kt, app/src/main/java/com/jerboa/ui/components/settings/lookandfeel/LookAndFeelActivity.kt, app/src/main/java/com/jerboa/ui/theme/Sizes.kt
- See https://github.com/alorma/Compose-Settings/issues/203
- Fixes #1338
=> Temp workaround for compose-settings height bug.

app/src/main/java/com/jerboa/datatypes/Utils.kt, app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt, app/src/main/java/com/jerboa/ui/components/comment/CommentOptionsDropdown.kt, app/src/main/java/com/jerboa/ui/components/comment/mentionnode/CommentMentionOptionsDropdown.kt, app/src/main/java/com/jerboa/ui/components/comment/reply/CommentReply.kt, app/src/main/java/com/jerboa/ui/components/comment/replynode/CommentReplyOptionsDropdown.kt
=> Dont show comment content when its deleted or removed.

app/src/main/java/com/jerboa/ui/components/comment/CommentOptionsDropdown.kt, app/src/main/java/com/jerboa/ui/components/comment/mentionnode/CommentMentionOptionsDropdown.kt, app/src/main/java/com/jerboa/ui/components/comment/replynode/CommentReplyOptionsDropdown.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfile.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileActivity.kt, app/src/main/java/com/jerboa/ui/components/post/composables/PostOptionsDropdown.kt, app/src/main/res/values/strings.xml
=> Adding ability to ban users from profile pages.

.woodpecker.yml, app/src/debug/res/values/strings.xml, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-az/strings.xml, app/src/main/res/values-bg/strings.xml, app/src/main/res/values-da/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-nn/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-se/strings.xml, app/src/main/res/values-uk/strings.xml
My release build failed because this task was missing. I'll add the fixes in a sec.
It had to do with some unecessary translations I removed. Once this passes I'll merge so I can do a release.
=> Adding lintVitalRelease to CI

app/src/main/java/com/jerboa/JerboaAppState.kt, app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/ui/components/common/Route.kt, app/src/main/java/com/jerboa/ui/components/home/legal/SiteLegalActivity.kt, app/src/main/java/com/jerboa/ui/components/home/sidebar/SiteSidebarActivity.kt, app/src/main/res/values/strings.xml
=> Adding legal / privacy policy info.

app/src/main/java/com/jerboa/model/CreatePostViewModel.kt, app/src/main/java/com/jerboa/ui/components/post/composables/PostComposables.kt, app/src/main/java/com/jerboa/ui/components/post/create/CreatePostActivity.kt, app/src/main/java/com/jerboa/ui/components/post/edit/PostEditActivity.kt
You can choose if you want this or the old the system.
Either way the eventual log viewer will be preferably.
[jerboa-app-debug.zip](https://github.com/dessalines/jerboa/files/14378255/jerboa-app-debug.zip)
@epragalakis
Can you install the above apk and show me which error you are getting
=> Show full error on post creation failing

app/src/main/java/com/jerboa/ui/components/common/AppBars.kt, app/src/main/java/com/jerboa/ui/components/drawer/Drawer.kt, app/src/main/java/com/jerboa/ui/components/drawer/DrawerActivity.kt, app/src/main/java/com/jerboa/ui/components/home/BottomNavActivity.kt
Should fix #1398 
That person was just a mod, and that action was banning users from an instance not from a community.
We don't have that action yet right that you can ban users from just a community?
=> Fix sidebar showing admin screen to all users

app/src/main/java/com/jerboa/ui/components/reports/ReportsActivity.kt
=> Fix that non admin mods can see messages report tab

README.md
=> Add nlnet grant line in readme.

build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
Leaving off the compose-settings updates for now, it still needs some work.
=> Upgrading deps.

app/src/main/java/com/jerboa/ui/components/common/Dialogs.kt
Minor additions here, just making sure it passes lint.
=> Fixing donation line.

app/schemas/com.jerboa.db.AppDB/33.json, app/src/main/java/com/jerboa/db/AppDB.kt, app/src/main/java/com/jerboa/db/AppDBMigrations.kt
I'm overwriting a few of these defaults, after testing on another device, that showed them being wrong.
=> Correcting a few wrong defaults.

app/build.gradle.kts
=> Revert "Set specific versions for runtime-livedata."

app/src/main/java/com/jerboa/ui/components/viewvotes/ViewVotes.kt
This got added recently to `0.19.4`
=> Show when banned on view-votes screen.

app/build.gradle.kts
Fixes #1596 
I tested this locally but you should too. It's upto you if you want to make another release.
=> Fix subscribed feed paging not working

app/build.gradle.kts
=> Fix dialog for switching keyboards/languages

app/src/main/java/com/jerboa/feat/Voting.kt, app/src/main/java/com/jerboa/ui/components/common/VoteHelpers.kt, app/src/main/java/com/jerboa/ui/components/post/PostListingList.kt
=> Showing scores in post listing like they were before.

app/src/main/java/com/jerboa/ui/components/common/PictrsImage.kt
- See https://github.com/coil-kt/coil/issues/1505
=> Temp fix for incorrect coil image sizing.

app/build.gradle.kts
No idea why renovate isn't picking up this one.
=> Upgrading compose-bom to 2024.08

app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt, app/src/main/java/com/jerboa/ui/components/comment/mentionnode/CommentMentionNode.kt, app/src/main/java/com/jerboa/ui/components/comment/replynode/CommentReplyNode.kt, app/src/main/java/com/jerboa/ui/components/community/Community.kt, app/src/main/java/com/jerboa/ui/components/home/Home.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfile.kt, app/src/main/java/com/jerboa/ui/components/post/PostListingCard.kt
Fixes #1675 
Fixes #1676 
Fixes #1677
=> Fix popups disappearing on orientation change.

app/src/main/java/com/jerboa/model/CommunityListViewModel.kt, app/src/main/java/com/jerboa/ui/components/community/list/CommunityListScreen.kt
Fixes #1678 
(With the option destroy activities)
https://github.com/user-attachments/assets/a22b38ba-de09-4fff-9552-d17b1da3b892
=> Fix community search not relaunching after process death

app/build.gradle.kts
- This would cause errors with izzyondroid releases.
=> Fixing signing config.

app/src/main/java/com/jerboa/ui/components/post/composables/PostComposables.kt, app/src/main/java/com/jerboa/ui/components/post/create/CreatePostScreen.kt, app/src/main/java/com/jerboa/ui/components/post/edit/PostEditScreen.kt
This adds an image upload button for the custom thumbnail field:
=> Adding an image upload button for custom thumbnails.

app/build.gradle.kts, app/src/main/java/com/jerboa/feat/AccountVerificationState.kt, app/src/main/java/com/jerboa/ui/components/home/BottomNavScreen.kt
Can't repro the crash but hopefully this will fix it.
Fixes #1757
=> Fix rare crash on switching account #1757

CONTRIBUTING.md, README.md
Switches to using weblate like all our other lemmy translations.
=> Adding weblate translations url.

app/src/main/java/com/jerboa/ui/components/imageviewer/ImageViewerScreen.kt
=> Fix deprecation zoomable constructor

app/src/main/java/com/jerboa/ui/components/post/PostListing.kt, app/src/main/java/com/jerboa/ui/components/post/PostListingCard.kt
https://github.com/user-attachments/assets/2a569857-2347-4fe9-a24a-b427c16d015c
Fixes #1870
=> Fix post read not being applied in smallcard viewmode #1870

app/schemas/com.jerboa.db.AppDB/34.json, app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/db/AppDB.kt, app/src/main/java/com/jerboa/db/AppDBMigrations.kt, app/src/main/java/com/jerboa/db/entity/AppSettings.kt, app/src/main/java/com/jerboa/ui/components/common/EmbeddedVideoPlayer.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityScreen.kt, app/src/main/java/com/jerboa/ui/components/home/BottomNavScreen.kt, app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileScreen.kt, app/src/main/java/com/jerboa/ui/components/post/PostListing.kt, app/src/main/java/com/jerboa/ui/components/post/PostListingCard.kt, app/src/main/java/com/jerboa/ui/components/post/PostListings.kt, app/src/main/java/com/jerboa/ui/components/post/PostScreen.kt, app/src/main/java/com/jerboa/ui/components/settings/lookandfeel/LookAndFeelScreen.kt, app/src/main/res/values/strings.xml
Most work was propdrilling that setting.
I ve been thinking about using compositionprovider to push the settings down, and only pass by arg in the relevant composables.
But that would be a lot of refactor work to setup initially and I don't know how you feel about it.
https://github.com/user-attachments/assets/23d7871c-cfac-4bd2-aacb-f54be517a847
=> Add option to disable video auto play
