README.md
Seeing as Jerboa has made it to the F-Droid repository, it is time to update the installation information from the README.
=> Add link to Jerboa on F-Droid

app/build.gradle, app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt, app/src/main/java/com/jerboa/ui/components/comment/edit/CommentEdit.kt, app/src/main/java/com/jerboa/ui/components/comment/edit/CommentEditActivity.kt, app/src/main/java/com/jerboa/ui/components/comment/reply/CommentReply.kt, app/src/main/java/com/jerboa/ui/components/comment/reply/CommentReplyActivity.kt, app/src/main/java/com/jerboa/ui/components/common/AppBars.kt, app/src/main/java/com/jerboa/ui/components/common/PictrsImage.kt, app/src/main/java/com/jerboa/ui/components/common/TextFields.kt, app/src/main/java/com/jerboa/ui/components/common/TimeAgo.kt, app/src/main/java/com/jerboa/ui/components/common/VoteHelpers.kt, app/src/main/java/com/jerboa/ui/components/community/Community.kt, app/src/main/java/com/jerboa/ui/components/community/list/CommunityList.kt, app/src/main/java/com/jerboa/ui/components/home/Home.kt, app/src/main/java/com/jerboa/ui/components/inbox/Inbox.kt, app/src/main/java/com/jerboa/ui/components/login/Login.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfile.kt, app/src/main/java/com/jerboa/ui/components/post/PostListing.kt, app/src/main/java/com/jerboa/ui/components/post/create/CreatePost.kt, app/src/main/java/com/jerboa/ui/components/post/edit/PostEdit.kt, app/src/main/java/com/jerboa/ui/components/private_message/PrivateMessage.kt, app/src/main/java/com/jerboa/ui/components/private_message/PrivateMessageReply.kt, app/src/main/java/com/jerboa/ui/components/report/CreateReport.kt, app/src/main/java/com/jerboa/ui/theme/Color.kt, app/src/main/java/com/jerboa/ui/theme/Theme.kt, app/src/main/java/com/jerboa/ui/theme/Type.kt
- Fix low contrast in light theme. Fixes #116
- Use proper muted text. Fixes #112
- Fix navbar colors. Fixes #111
=> Various Light theme fixes.

app/src/main/java/com/jerboa/ui/theme/Theme.kt
Hello!
I noticed while using Jerboa that while my phone is using the dark theme, the status bar icons within the app are also dark which makes it seem a bit out of place. I'm opening this pull request to try to resolve this issue. I'm pretty new to the Jetpack Compose toolkit, so hopefully this approach looks appropriate. The following are screenshots from before and after to demonstrate the change:
Before:
After:
I tested this on my physical Pixel 6a running Android 13, however as a precaution I went ahead and also tested this on a virtual Pixel 3a running Android 11, just to make sure there were no introduced incompatibility changes.
=> Adjust the status bar while using the system dark theme to not use dark icons

app/src/main/java/com/jerboa/ui/components/home/Home.kt, app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt
Right now the only way to access the settings menu is to first log in to an account. This change shows the settings menu button in the drawer even when not logged in.
=> Show settings in sidebar even when user is not logged in

build.gradle
This makes it so that an alpha-build of Android Studio is not necessary to contribute to the project.
=> Roll back AGP to `8.0.2`

.editorconfig, build.gradle
`ktlint` follows the rules in this file.
For the sake of simplicity, the rules in the file are aligned with what's in place in the project already. No additional formatting is necessary after this PR is merged.
=> Add `.editorconfig`

app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/ui/theme/Theme.kt
Added Black theme mode. Looks exactly like the Dark theme mode except near-black background colors are true black. Also added theme mode SystemBlack, which uses Light/Black instead of Light/Dark depending on system setting. Fixes https://github.com/dessalines/jerboa/issues/376.
=> Added Black and System Black theme modes, fixes https://github.com/dessalines/jerboa/issues/376

app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt, app/src/main/java/com/jerboa/ui/components/comment/mentionnode/CommentMentionNode.kt, app/src/main/java/com/jerboa/ui/components/comment/reply/CommentReply.kt, app/src/main/java/com/jerboa/ui/components/comment/replynode/CommentReplyNode.kt, app/src/main/java/com/jerboa/ui/components/common/AppBars.kt, app/src/main/java/com/jerboa/ui/components/common/Dialogs.kt, app/src/main/java/com/jerboa/ui/components/common/InputFields.kt, app/src/main/java/com/jerboa/ui/components/home/Home.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfile.kt, app/src/main/java/com/jerboa/ui/components/post/PostListing.kt, app/src/main/java/com/jerboa/ui/components/privatemessage/PrivateMessage.kt
Users can now collapse comments by tapping anywhere on the comment body or header, and expand comments again by tapping on the comment header. This replaces the old behaviour (tap and hold on comment headers), which wasn't as intuitive for new users.
Tested on comment markdown text as well as "View source" comment text. Tested clickable links in the comment body and usernames in the comment header are still clickable.
=> Collapse comments by tapping directly on the comment body

app/src/main/java/com/jerboa/MainActivity.kt
This fixes an issue where the app crashes/restarts when a user or community in a different instance is clicked within a comment.
I've changed the routes slightly so the name given ends up being `name@instance` instead of just `name`
Fixes [#395](https://github.com/dessalines/jerboa/issues/395)
=> Fix navigating to other instance communities and users

app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/db/AppDB.kt, app/src/main/java/com/jerboa/ui/components/common/AppBars.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityActivity.kt, app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt, app/src/main/java/com/jerboa/ui/components/inbox/InboxActivity.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileActivity.kt, app/src/main/java/com/jerboa/ui/components/settings/lookandfeel/LookAndFeelActivity.kt
This adds a checkbox option to disable the bottom navigation bar throughout the app. Testing locally it seems to work correctly, including migrations.
=> Add option to disable showing the bottom navigation bar

app/src/main/java/com/jerboa/ui/components/settings/lookandfeel/LookAndFeelActivity.kt
This moves the `updateAppSettings` function to be an inner function of `LookAndFeelActivity`. Now we don't have to pass every state object for every single settings entry.
=> Use inner function to reduce boilerplate in LookAndFeelActivity

app/src/main/java/com/jerboa/MainActivity.kt
During transitions the window background (default white) is displaying. When using a dark theme this looks like a flash.
Making the window background transparent uses the themes color instead.
=> Fix the flashing between transitions (#371)

app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt, app/src/main/java/com/jerboa/ui/components/common/AppBars.kt
This allows the user to tap in the action bar, as well as disables the animation in the header bar in a comment.
=> Expand area tappable by user to collapse a comment

app/src/main/java/com/jerboa/ui/components/common/AppBars.kt, app/src/main/java/com/jerboa/ui/components/login/Login.kt, app/src/main/java/com/jerboa/ui/theme/Theme.kt
* Disabled autocorrection in the login form's instance field.
* Added some padding to the top of the login button.
* Set the status and navigation bar colors depending on the chosen theme.
* Also set the navigation color depending on the bottom app bar visibility.
=> Aesthetics improvements

app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/ui/components/login/Login.kt
=> Enable autofill on login form

app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/db/AppDB.kt, app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt, app/src/main/java/com/jerboa/ui/components/comment/CommentNodes.kt, app/src/main/java/com/jerboa/ui/components/comment/reply/CommentReply.kt, app/src/main/java/com/jerboa/ui/components/common/AppBars.kt, app/src/main/java/com/jerboa/ui/components/common/TimeAgo.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostActivity.kt, app/src/main/java/com/jerboa/ui/components/settings/lookandfeel/LookAndFeelActivity.kt
Basic functionality is working, but still a few TODOs on this:
- ~No indication if a comment is collapsed since the whole body is shown. Boost uses a little +N icon in the top bar.~
- ~Comments folding isn't animated currently~
- ~Settings migrations needs to be tested~
=> Add option to show contents of collapsed comments

app/build.gradle, app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/ui/components/common/InputFields.kt, app/src/main/java/com/jerboa/ui/components/common/MarkdownHelper.kt, app/src/main/java/com/jerboa/ui/theme/Type.kt
Images show at approx 45% size in the markdown renderer.
This allows us to remove the markdown scaling applied to the editor which forced the text content to also be increased which made it inconsistent with the rest of the app.
Removed the compose-markdown package and created our own wrapper around the markwon libraries with a custom resolver for images.
#373
=> Markdown renderer replacement

app/build.gradle, app/src/main/java/com/jerboa/ui/components/common/MarkdownHelper.kt
This adds the linkify plugin to markwon. This will allow links to be automatically detected and made clickable, even if that link isn't formatted as a markdown link. I also added a second plugin to configure links rendered by markwon to be opened using our `openLink` function, intended for future use like custom tabs, special handling of detected fediverse links, etc.
=> Add linkify plugin to markwon

app/src/main/java/com/jerboa/ui/components/post/create/CreatePostActivity.kt
According to flutter's app:compileDebugKotlin job, in the context of CreatePostActivity.kt, 'uri != null' is always 'true'.
=> Remove unnecessary check

app/src/main/java/com/jerboa/ui/components/common/InputFields.kt, app/src/main/java/com/jerboa/ui/components/settings/account/AccountSettings.kt
| Before  | After |
| ------------- | ------------- |
| ![](https://github.com/dessalines/jerboa/assets/2427877/f5dcc32b-5fa3-4ca0-b042-1046b3a952f9)  | ![](https://github.com/dessalines/jerboa/assets/2427877/1ebc2eae-d85b-44b1-831d-d0a0cccb742b)  |
| ![](https://github.com/dessalines/jerboa/assets/2427877/f5113577-b0cc-4c55-8d9b-3f45e352a58b)  | ![](https://github.com/dessalines/jerboa/assets/2427877/2ffbd0b7-5855-4ba5-8d5a-932ffc335836)  |
=> Account Settings: Improves paddings and small layout details

app/src/main/java/com/jerboa/Utils.kt, app/src/test/java/com/jerboa/UtilsKtTest.kt
This is a partial fix to #556, but it at least prevents crashing when an unknown URL type is encountered. There is still some work to do, since the markdown plugin interprets the following as mailto: urls:
- @user@instance
- !community@instance
I'm not sure what the supported URL types are intended to be, so I didn't bother implementing a plugin.
=> Handle /c/community@host URLs

app/src/main/java/com/jerboa/ui/components/common/VoteHelpers.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityLink.kt, app/src/main/res/values/strings.xml
- Dropped "todo" from the community icon description
- Changed "Select listing filter" to "select feed"
- Changed "Select sort option" to "sort by"- this affects multiple components
- Changed "Show more options" to "more options"
- Changed the way vote component descriptions are written. The type and vote are used to select among "upvote", "upvoted", "downvote", and "downvoted"
- Changed "Select inbox filter" to "filter"
Fixes #616
=> Small Accesibility Tweaks

app/src/main/java/com/jerboa/ui/components/post/create/CreatePost.kt
resolves #602 This changes the submit icon from `add` to `submit` and adds a preview for the post header.
=> #602 Change post button to be more obvious

app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt
Changed icons for "Go to comment" and "Copy permalink" in CommmentOptionsDialog to "Icons.Outlined.Forum" and "Icons.Outlined.Link"
Closes #779
=> Changed icons for "Go to comment" and "Copy permalink" in CommmentOptionsDialog

app/src/main/java/com/jerboa/Utils.kt, app/src/test/java/com/jerboa/UtilsKtTest.kt
Apparently I broke stuff by trying to be fancy. I'm not really a fan of parsing the URL like this though, but at least there are test cases for it now.
=> Fix bug with pictrs url query param rewriting

app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityActivity.kt, app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostListing.kt, app/src/main/java/com/jerboa/ui/components/post/PostListings.kt
Somewhere along the line, clicking on thumbnail links got removed, and every thumbnail was treated as an image, even if it was a link post.
This fixes that by altering the thumbnail tile to check to see if the url is an image.
=> Fix thumbnail links being treated as images. Fixes #815

app/src/main/java/com/jerboa/ui/components/community/list/CommunityList.kt
All other tabs use the back arrow while the search page (`CommunityListActivity`) uses the 'X'.
This PR fixes that so the back buttons are consistent.
=> Make Search Page have consistent back button

app/src/main/java/com/jerboa/ui/components/common/MarkdownHelper.kt
Closes #730 
Closes #825 
This happens only with images that go beyond the available canvas width. The attached videos shows 2 images one after another and the jerk down only occurs for the larger image which is of res 1600x1200 while only 990px was the available width.
This seems to be a problem with the `CoilImagePlugin` (or maybe that's how it's meant to behave) which doesn't call the image resolver if the canvas width is not known. The canvas width is obtained during the first paint call.
So, the initial bounds are 1600x1200 and during the first paint call, it realizes the image won't fit and reduces the bounds based on the canvas width. My assumption is this change in bounds is picked up by the lazy column and the jerk down happens trying to maintain the scroll position.
Other ways …
=> Fix for scrolling up past images in the comments jerks you back down

app/src/main/java/com/jerboa/ui/components/post/composables/PostComposables.kt, app/src/main/java/com/jerboa/ui/components/post/create/CreatePost.kt, app/src/main/java/com/jerboa/ui/components/post/create/CreatePostActivity.kt, app/src/main/java/com/jerboa/ui/components/post/edit/PostEdit.kt, app/src/main/java/com/jerboa/ui/components/post/edit/PostEditActivity.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values/strings.xml
Closes #679 
Added a switch to `CreatePost.kt` and `PostEdit.kt` and added logic to the corresponding activities.
=> Added switch to mark new posts as NSFW / toggle tag on existing posts

app/src/main/java/com/jerboa/ui/components/common/ImageViewerDialog.kt
This closes #892 
With my PR #738 I broke the intended functionality of `com.jerboa.ui.components.common.ImageViewerDialog.kt`.
**The originally intended functionality was:**
* tap dialog to hide / show top icon bar
* double tap to zoom in 
* double tap + drag to zoom in and out
**My mistake:**
I added a `.clickable` modifier to the image. This overwrote the indended functionality (...and added a white overlay according to @pipe01 which I honestly could not reproduce)
**My solution in this PR:**
I removed the `.clickable` modifier to restore the original functionality and also added the `.scrollable` modifier to the surrounding box. The box now listens to a scroll gesture and dismisses the dialog if it detects a scroll with a delta < -70. This translates to a "quickly swipe up" gesture.
=> Fix .zoomable functionality in ImageViewerDialog and add "swipe up to close"

app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/db/AppDB.kt, app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt, app/src/main/java/com/jerboa/ui/components/comment/CommentNodes.kt, app/src/main/java/com/jerboa/ui/components/comment/mentionnode/CommentMentionNode.kt, app/src/main/java/com/jerboa/ui/components/comment/replynode/CommentReplyNode.kt, app/src/main/java/com/jerboa/ui/components/common/AccountHelpers.kt, app/src/main/java/com/jerboa/ui/components/common/PictrsImage.kt, app/src/main/java/com/jerboa/ui/components/community/Community.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityActivity.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityLink.kt, app/src/main/java/com/jerboa/ui/components/community/list/CommunityList.kt, app/src/main/java/com/jerboa/ui/components/community/list/CommunityListActivity.kt, app/src/main/java/com/jerboa/ui/components/home/BottomNavActivity.kt, app/src/main/java/com/jerboa/ui/components/home/Home.kt, app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt, app/src/main/java/com/jerboa/ui/components/inbox/InboxActivity.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostListing.kt, app/src/main/java/com/jerboa/ui/components/post/PostListings.kt, app/src/main/java/com/jerboa/ui/components/post/composables/PostComposables.kt, app/src/main/java/com/jerboa/ui/components/settings/lookandfeel/LookAndFeelActivity.kt, app/src/main/res/values/strings.xml
Add a blur option in settings, that controls if NSFW images should be blurred.
Fix community icons and banners not being blurred for NSFW communities
Refactor app setting defaults, previously app settings default where littered all over the place. If we wanted to change a default we would have to track down a dozen places. Now it is all stored in a central location.
Fixes #529
Makes #514 obsolete and can be closed
Tested on android 13 & 11
=> Add blur option, fix non blurred community icons/banners

app/src/main/java/com/jerboa/ui/components/comment/edit/CommentEditActivity.kt
Fixes the edit comment view being empty
It was composed first before the initialize was called which sets the commentView. Causing it to set the remember with empty text. I changed the remember to change when commentView changes. Not sure if it is normal that it compose before initialize fires. @nahwneeth ?
Fixes #895 
https://github.com/dessalines/jerboa/assets/67873169/12ccdcee-6aca-46a1-96c9-cca6d416809a
=> Fix edit comment view text is being empty

app/src/main/res/values-da/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-se/strings.xml, app/src/main/res/values/strings.xml, fastlane/metadata/android/en-US/title.txt
This will change the name shown on the android home screen and settings to `Jerboa` while leaving the name on the Play Store as `Jerboa for Lemmy`
This gives a bit of a cleaner look as long app names will either overflow to a new line or will be truncated with an ellipse (eg. `Jerboa for Le...`) but will retain the searchability for users searching "Lemmy" on the Play Store and it's still clear from the title what the app is for.
This does remove the localization but I believe it should be possible to restore this by creating a title.txt file in the respective locale folder under `fastlane/metadata/android/`, although I don't know Fastlane well enough to confirm this.
=> Change app display name

CONTRIBUTING.md, app/update_instances.gradle.kts
There were basically two problems:
- Task was calling functions defined in the script. Fixed it by moving everything into a proper task class.
- Task was calling `Project.file`. Replaced it with file output properties. Since task now had defined inputs/outputs it would be cacheable, so I made it not tracked (not cacheable and never up-to-date).
=> Make updateInstances task compatible with configuration cache

app/src/main/java/com/jerboa/ui/components/settings/about/AboutActivity.kt, app/src/main/res/drawable/ic_jerboa.xml
In 7d9c5a68c47f568d5a17f6630450e2bd267220ac the jerboa icon changed size, but the paths were still at the previous size.
Converted the drawable to SVG, resized using `rsvg-convert`, then exported back to a drawable.
Before:
After:
=> Fix jerboa icon resize.

app/src/main/java/com/jerboa/api/Http.kt, app/src/main/java/com/jerboa/util/CustomHttpLoggingInterceptor.kt, app/src/main/java/com/jerboa/util/DisableLog.kt
Add CustomHttpLoggingInterceptor, remove old way
This way is better than the previous as it only redacts the fields we don't want to log. Previously entire requests where not being logged. Making it harder to debug if those requests (such as login) where actually being done.
Fixes #919
=> Fix JWT from being logged

app/src/main/java/com/jerboa/ui/components/common/AppBars.kt, app/src/main/java/com/jerboa/ui/components/home/BottomNavActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostListing.kt
There where some left behind depreciations from upgrading to compose 15.3
=> Fix deprecations

app/src/main/java/com/jerboa/ui/components/common/Navigation.kt
The current approach had issue, and that was noticeable when u tried returning from after you logged in.
Here demo of it allowing you to go back on login.
https://github.com/dessalines/jerboa/assets/67873169/c9baa6bd-6916-446f-91bc-fbbbe827f5cd
How it is now fixed
https://github.com/dessalines/jerboa/assets/67873169/917ab0f4-bff0-43f2-95ee-88d8d5688063
see https://stackoverflow.com/a/74993733/16066673
=> Fix clear backstack not working properly

app/src/main/java/com/jerboa/ui/components/common/AppBars.kt
Fixes a visual regression due to a change in made in which I fixed some deprecations #962 
Old:
Now and what it was before:
=> Fix regression due to deprecations change

app/src/main/java/com/jerboa/ui/components/community/CommunityLink.kt
Adds ellipsis textoverflow to community names.
Names are now shorted using ...
Does not affect community names on their page
Fixes #983 
Fixes #775
=> Add "..." for too long community names

app/src/main/java/com/jerboa/model/InboxViewModel.kt, app/src/main/java/com/jerboa/ui/components/inbox/InboxActivity.kt
Fix inbox loading all pages on startup instead of set unread/all mode.
Fixes #1006
=> Fix inbox loading all pages on startup instead of set unread/all mode

app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/Utils.kt
Fix a rare crash when deleting the app DB while the app is still open. On relaunch it will return a null even though it should not.
Crash log
Before
https://github.com/dessalines/jerboa/assets/67873169/e7325f58-6ba1-4317-8aba-1bc5c4f3cc70
After: You can barely see it but it relaunches on startup
https://github.com/dessalines/jerboa/assets/67873169/e3dccba6-2219-424c-8d71-59ecc82096aa
=> Fix rare edgecase crash when deleting app DB

app/schemas/com.jerboa.db.AppDB/21.json, app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/db/AppDB.kt, app/src/main/java/com/jerboa/db/AppDBMigrations.kt, app/src/main/java/com/jerboa/db/entity/AppSettings.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityActivity.kt, app/src/main/java/com/jerboa/ui/components/home/BottomNavActivity.kt, app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostListing.kt, app/src/main/java/com/jerboa/ui/components/post/PostListings.kt, app/src/main/java/com/jerboa/ui/components/settings/lookandfeel/LookAndFeelActivity.kt, app/src/main/res/values/strings.xml
In an issue somewhere someone suggested that titles and bodies were being duplicated when it was actually just that the user copied the title and article description into their post. I thought maybe adding an option to disable the preview would be a good idea.
When enabled/current behavior:
After with disabled:
=> Add option to show/hide post previews

app/src/main/res/values-de/strings.xml
Hi,
I've added some missing translations and also changed some of the translated words:
The translation of "Inbox" was changed to "Inbox" (the same), since this word is in the german dictionary (https://www.duden.de/rechtschreibung/Inbox) and has the same meaning.
The translation of "Saved" was changed to "Markiert" (meaning: marked), instead of a more direct translation "Gespeichert" (meaning: saved), since this would probably be too long.
=> Add missing and shorten some german translations (fixes #818)

app/src/main/java/com/jerboa/ui/components/drawer/Drawer.kt
Currently when selecting Subscribed/Local/All when any tab other than Home is selected, nothing appears to happen. This change navigates back to home to show the user the feed they selected.
=> Navigate to home tab after selecting feed type in sidebar

app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt
Right now it currently draws the divider on top of the border which is kinda weird when you look closely.
=> Show comment divider inside the left side border

app/src/main/java/com/jerboa/model/LoginViewModel.kt, app/src/main/java/com/jerboa/ui/components/login/Login.kt, app/src/main/res/values/strings.xml
Fixes #987 
https://github.com/dessalines/jerboa/assets/67873169/8fbaf24c-07cb-4616-a721-10d9bfa8e4ed
I used name + instance to define duplicate because person.Id could be duplicate for two separate accounts on different instances.
I do feel like this whole login function with its numerous changeLemmyInstances should be refactored to use createTempInstance and only be swapped on login.
=> Prevent duplicate accounts from logging in

app/src/main/java/com/jerboa/ui/components/drawer/Drawer.kt, app/src/main/java/com/jerboa/ui/components/drawer/DrawerActivity.kt, app/src/main/res/values/strings.xml
Small QoL, many times I wanna test something in anon but I dont want to remove my currently logged in account. This will solve that.
https://github.com/dessalines/jerboa/assets/67873169/b4858b5d-4eaf-4cbe-b2fe-f54a763017c5
=> Add switch to anonymous option

app/src/main/java/com/jerboa/api/Http.kt, app/src/main/java/com/jerboa/model/SiteViewModel.kt, app/src/main/java/com/jerboa/ui/components/inbox/InboxActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostListing.kt
- Fixes missing redaction of AUTH in body
- Fixes refresh not getting unreadCount
- Removes the API calls for unreadCount on markRead by applying smart logic
- Fixes clicking on a read reply marking it as unread
https://github.com/dessalines/jerboa/assets/67873169/526cc611-4efc-4289-b28a-02afeec6e3e6
=> Fetch unreadCount on refresh, make unreadCount use less API calls, fix mark unread reply bug

app/src/main/java/com/jerboa/Utils.kt, app/src/main/res/values/strings.xml
See https://github.com/dessalines/jerboa/pull/1102#issuecomment-1653552240.
=> Add long-form ‘Top All’ string

app/src/main/java/com/jerboa/api/Http.kt
Fixes these
Currently it always assumes that when the response fails that it gets a JSON error object. Which we frequently don't.
So this will make `timeout` errors and others show nicely
Fixes #1005
=> Fix `Value X cannot be converted to json` in error messages 

app/src/main/res/values-es/strings.xml
In this context "Inbox" can be translated as "Entrada" instead of "Bandeja de Entrada" and thus avoid breaking the bottom navbar.
=> Fix Inbox Spanish Translation, closes #1110

app/src/main/java/com/jerboa/ui/components/comment/reply/CommentReply.kt, app/src/main/java/com/jerboa/util/AccountVerificationState.kt, app/src/main/res/values/strings.xml
I am not 100% sure but I believe account approval and email approval should only be done during login. The instance owner could turn these on after they are logged in and then it should not impede the the user but these checks will.
I also added account banned but I am unsure if a banned user can still do actions with his account. So I assumed not.
=> Remove account_approved and account_email_verified add account_banned checks

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/ui/components/imageviewer/ImageViewerActivity.kt, app/src/main/java/com/jerboa/util/UserActions.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/file_provider_paths.xml
Add share button to the imageviewer,
also fixed the issue where it would cancel the download if you closed the imageviewer before it finishes. Also made the download now check the cache first to prevent unnecessary network call and it uses httpClient.
Remove permission dep, as I don't like permission stuff being a composable. Limits future reuse
=> Add share functionality to imageviewer

app/build.gradle.kts, app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/ui/components/post/create/CreatePostActivity.kt, app/src/main/java/com/jerboa/ui/components/post/edit/PostEditActivity.kt, app/src/main/res/values/strings.xml, app/src/test/java/com/jerboa/UtilsKtTest.kt
Fixes #1129 
Pulls in Mockito. I'm not sure what the feeling about doing so is. 
Just wanted to be able to keep the tests while also mocking `Context` out.
=> Add strings for the validateUrl and validatePostName utils.

app/src/main/java/com/jerboa/ui/components/common/DropdownMenu.kt, app/src/main/java/com/jerboa/ui/components/community/Community.kt, app/src/main/java/com/jerboa/ui/components/home/Home.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfile.kt
This does some of the work for #1065 by moving more/three-dot buttons on top app bars over to use dropdowns rather than dialogs.
Whether to move other dialogs to dropdowns has some concerns in that issue (such as scrollable areas) and might be facilitated by other components, so this is limited intentionally.
=> Make app bar 'more' buttons use dropdowns rather than dialogs

app/src/main/java/com/jerboa/ui/components/common/Dialogs.kt, app/src/main/java/com/jerboa/ui/components/common/DropdownMenu.kt, app/src/main/java/com/jerboa/ui/components/home/Home.kt, app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt
part of #1065
https://github.com/dessalines/jerboa/assets/67873169/c3bf7b1b-f300-43d8-8006-2f667b2d9513
=> Use listing type use M3 dropdown instead of dialog

app/schemas/com.jerboa.db.AppDB/24.json, app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/datatypes/SampleData.kt, app/src/main/java/com/jerboa/db/AppDB.kt, app/src/main/java/com/jerboa/db/AppDBMigrations.kt, app/src/main/java/com/jerboa/db/entity/Account.kt, app/src/main/java/com/jerboa/db/entity/AppSettings.kt, app/src/main/java/com/jerboa/feat/AccountVerificationState.kt, app/src/main/java/com/jerboa/feat/BackConfirmation.kt, app/src/main/java/com/jerboa/feat/PostActionbarMode.kt, app/src/main/java/com/jerboa/model/AccountViewModel.kt, app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt, app/src/main/java/com/jerboa/ui/components/comment/edit/CommentEditActivity.kt, app/src/main/java/com/jerboa/ui/components/comment/mentionnode/CommentMentionNode.kt, app/src/main/java/com/jerboa/ui/components/comment/replynode/CommentReplyNode.kt, app/src/main/java/com/jerboa/ui/components/common/AppBars.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityActivity.kt, app/src/main/java/com/jerboa/ui/components/home/BottomNavActivity.kt, app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt, app/src/main/java/com/jerboa/ui/components/inbox/InboxActivity.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostListing.kt, app/src/main/java/com/jerboa/ui/components/post/PostListings.kt, app/src/main/java/com/jerboa/ui/components/privatemessage/PrivateMessage.kt, app/src/main/java/com/jerboa/ui/components/settings/lookandfeel/LookAndFeelActivity.kt, app/src/main/res/values/strings.xml, app/src/release/generated/baselineProfiles/baseline-prof.txt
=> Post actionbar design rework and options for it.

app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt, app/src/main/java/com/jerboa/ui/components/comment/mentionnode/CommentMentionNode.kt, app/src/main/java/com/jerboa/ui/components/comment/replynode/CommentReplyNode.kt, app/src/main/java/com/jerboa/ui/components/post/PostListing.kt, app/src/main/res/values-az/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-nn/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values/strings.xml
Also makes it easier to make selections on comment source, and source now shows in monospace.
[Screen_recording_20230812_000054.webm](https://github.com/dessalines/jerboa/assets/494446/5adf8621-d93e-4ee4-9794-f96673e49455)
=> Fix comment click deadzones

app/src/main/java/com/jerboa/Utils.kt
I changed it so that when it fails to retrieve `activeNetwork` due to possible revoke of the ACCES_NETWORK_STATE permission that it still passes the test. If the user actually has no internet the next steps will catch it in a real word api fetch.
=> Change the default of isCurrentlyConnected

app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/model/CommunityViewModel.kt, app/src/main/java/com/jerboa/ui/components/community/Community.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityActivity.kt, app/src/main/res/values/strings.xml
- Made text not hardcoded anymore
- Display error on failure to block
- Update view to show unblock if community is blocked
https://github.com/dessalines/jerboa/assets/67873169/520d9b43-de7c-43f2-b07b-648c5f5e7f67
I tried to do the same for postlistings but PostView does not contain a field for blocked community and mapping it to a datatype that does contain it pretty complex and could be done easier when the API rework gets done.
Also see https://github.com/LemmyNet/lemmy/issues/3885
=> Update community block msg to display unblock if blocked already

app/src/main/res/values-ja/strings.xml
This caused a crash every time you entered Community Info if your phone language is set to Japanese.
=> Fix broken Japanese string format for AppBars_users_month

app/src/main/java/com/jerboa/ui/components/common/AppBars.kt
Still see lots of issues with nav text overlapping, I see that other G apps have also rather smaller nav text. So I changed ours to be smaller too. Hopefully this fixes all the issues.
Fixes #1180
=> Make nav text smaller

app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/feat/UserActions.kt, app/src/main/res/values/strings.xml
Learned quite a bit from this. The original share/download since the introduction of the caching check was only really working in some instances due to some quirks. 
mistakes:
- scope.launch won't rethrow unhandled exceptions but will cancel its parents thus bypassing the try catch I had
- shareMedia used scope.launch for the IO part but it did not actually wait for this complete, thus it was sharing empty files at best crash at worst due to two sources reading/write to a cache file (only really worked in the rare instance its called from imageviewer where the image is loaded in cache and it wins the race condition on reading the file into the cached file)
-  Context.getInputStream shared a closed inputStream, the implementation for snapshot doesn't actually check if it is closed thus …
=> Fix crash in share Media, fix failed download media

app/src/main/java/com/jerboa/api/Http.kt, app/src/main/java/com/jerboa/model/CommunityViewModel.kt, app/src/main/java/com/jerboa/model/HomeViewModel.kt, app/src/main/java/com/jerboa/model/InboxViewModel.kt, app/src/main/java/com/jerboa/model/PersonProfileViewModel.kt, app/src/main/java/com/jerboa/ui/components/common/ApiStateHelpers.kt, app/src/main/java/com/jerboa/ui/components/common/Buttons.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityActivity.kt, app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostListings.kt, app/src/main/res/values/strings.xml
- Add button to retry loading more posts if it fails
- Removed page locking
- Add padding so that ApiError is not hiding behind header #1187 
This should provide a better UX than scrolling up and down again to initiate another attempt. The only thing I am not sure of is that should we auto scroll to that button? Most time it appears behind the bottom nav and only visible upon scrolling up.
Fixes #806
Fixes #1003
=> Add retry button when loading more posts fails

app/src/main/java/com/jerboa/ui/components/common/AppBars.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityActivity.kt, app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt, app/src/main/java/com/jerboa/ui/components/inbox/InboxActivity.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostActivity.kt
PullRefreshingIndicator uses Material thus it doesn't work with M3 Theming. So I fixed it.
Also fixed the placement being weird. Instead of doing that offset I had to just add the padding instead. Only on some pullrefreshindicators if they have a header. Those pagers seems to work fine out the box.
Fixes #1095 
Fixes #1011
=> Fix PullRefreshIndicator theming and placement

app/src/main/java/com/jerboa/model/SiteViewModel.kt
Fixes #1222 
@0xFOSSMan 
Sorry about before but this one can be trivially solved by resetting the unreadCount response to empty again.
Since we using derivativedState it will trigger on changes to unreadCountRes. Where `getUnreadCountTotal` sets it to zero for that ApiState
=> Fix unread count not resetting when swapping to anon

app/build.gradle.kts, app/src/main/java/com/jerboa/ui/components/imageviewer/ImageViewerActivity.kt
We used nested scrolling before to enable flick to exit behaviour, But nested scrolling doesn't work well compose and causes subtle issues. Thus I replaced it this with library which uses dragged instead.
see https://programming.dev/post/2375491
Fixes #1232
https://github.com/dessalines/jerboa/assets/67873169/c1ad26f5-3228-498e-8606-f629de7471ad
=> Fix zooming difficulties

app/src/main/java/com/jerboa/model/CommunityListViewModel.kt, app/src/main/java/com/jerboa/ui/components/community/list/CommunityListActivity.kt
This was a regression introduced in #1208. On return it would repopulate the searchlist with the user their followed communities. Now it only does it on navigation to the search.
https://github.com/dessalines/jerboa/assets/67873169/e1d1508e-c179-4515-8bbf-31a7c1f5a546
=> Fix search list repopulating on return

app/src/main/java/com/jerboa/ui/components/community/Community.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityActivity.kt
I found that there is no button to share a community url. This patch fixes that.
Not sure if this is the best way to create a community URL, let me know if I am missing something.
Also not sure if https can be expected from all instances. Didn't find any places were instance / community URLs are already created.
=> Community: Add Share drop down in community view.

gradle.properties
Lowering the gradle memory fixed all other android builds on our CI machines, so this should be done for gradle too.
=> Fix CI instability by lowering gradle memory.

app/src/main/java/com/jerboa/feat/AccountVerificationState.kt, app/src/main/java/com/jerboa/model/PersonProfileViewModel.kt
Fixes #1268 
Contains some other small refactorings, that I was working on
=> Fix missing deduplication guard on profile

app/src/main/java/com/jerboa/JerboaAppState.kt, app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/ui/components/post/create/CreatePostActivity.kt, app/src/test/java/com/jerboa/UtilsKtTest.kt
Fixes a crash on creating post. Since the datatypes are no longer a parcelable. They can't be saved directly into rememberSaveables. There might be more of these cases. 
Also fixed #1281 by appending https when needed
=> Fix crash on creating Post

app/src/main/java/com/jerboa/api/Http.kt, app/src/main/java/com/jerboa/feat/AccountVerificationState.kt
It was easier to solve than I originally thought. We already check if the instance is alive. So only after we make the API (In a safe manner)
Fix  #1289
=> Better fix for API creation in Verification procedure

app/build.gradle.kts, app/src/main/java/com/jerboa/db/entity/Account.kt, app/src/main/java/com/jerboa/feat/AccountVerificationState.kt
Fix #1294
Also fix a weird edge case were it seemed it didn't delete the existing user on trying to login again through the Verification action (It deletes your account)
Another thing we might want to do. Currently it throws a error with already signed in with this account error if trying to login again. We can give an option to replace the existing account?
=> Fix logging in failing

.woodpecker.yml
Same as https://github.com/LemmyNet/lemmy/pull/4276:
- Fail CI run on cache error so that we can actually notice and fix problems
- Increase timeout for cache operations (default is only 3m)
- Disable cache compression (takes unnecessary time)
Also change cache rebuild to run only on main branch, to prevent random attackers from writing into the cache from a PR.
=> Woodpecker CI cache fixes

.woodpecker.yml
There's a good chance this cache doesn't actually save any time.
=> Try removing meltwater cache.

.editorconfig, app/src/main/java/com/jerboa/datatypes/Others.kt, app/src/main/java/com/jerboa/datatypes/SampleData.kt, app/src/main/java/com/jerboa/datatypes/Utils.kt, app/src/main/java/com/jerboa/ui/components/common/InputFields.kt, app/src/main/java/com/jerboa/ui/components/common/Modifiers.kt, app/src/main/java/com/jerboa/ui/components/common/PictrsImage.kt, app/src/main/java/com/jerboa/ui/components/inbox/InboxActivity.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileActivity.kt, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-bg/strings.xml, app/src/main/res/values-nn/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-uk/strings.xml, benchmarks/build.gradle.kts
I am not sure what `pagerTabIndicatorOffset2` was used for, I removed it and I can't tell a difference
=> General changes

CONTRIBUTING.md, app/build.gradle.kts, app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/feat/ModActions.kt, app/src/main/java/com/jerboa/model/AppSettingsViewModel.kt, app/src/main/java/com/jerboa/model/CommunityListViewModel.kt, app/src/main/java/com/jerboa/model/SiteViewModel.kt, app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt, app/src/main/java/com/jerboa/ui/components/comment/CommentNodes.kt, app/src/main/java/com/jerboa/ui/components/comment/mentionnode/CommentMentionNode.kt, app/src/main/java/com/jerboa/ui/components/common/Modifiers.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityActivity.kt, app/src/main/java/com/jerboa/ui/components/community/list/CommunityListActivity.kt, app/src/main/java/com/jerboa/ui/components/drawer/Drawer.kt, app/src/main/java/com/jerboa/ui/components/drawer/DrawerActivity.kt, app/src/main/java/com/jerboa/ui/components/home/Home.kt, app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt, app/src/main/java/com/jerboa/ui/components/login/Login.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostListing.kt, app/src/main/java/com/jerboa/ui/components/post/PostListings.kt, build.gradle.kts, compose_compiler_config.conf
Compose metrics before:
```json
{
"skippableComposables": 568,
"restartableComposables": 868,
"readonlyComposables": 1,
"totalComposables": 880,
"restartGroups": 868,
"totalGroups": 1206,
"staticArguments": 1847,
"certainArguments": 696,
"knownStableArguments": 10855,
"knownUnstableArguments": 408,
"unknownStableArguments": 11,
"totalArguments": 11274,
"markedStableClasses": 4,
"inferredStableClasses": 82,
"inferredUnstableClasses": 34,
"inferredUncertainClasses": 1,
"effectivelyStableClasses": 86,
"totalClasses": 121,
"memoizedLambdas": 1055,
"singletonLambdas": 306,
"singletonComposableLambdas": 170,
"composableLambdas": 443,
"totalLambdas": 1324
}
```
Compose metrics after:
```json
{
"skippableComposables": 642,
"restartableComposables": 868,
"readonlyComposables": 1, …
```
=> Remove ImmutableList and add stability config file

app/src/main/java/com/jerboa/feat/ModActions.kt, app/src/main/java/com/jerboa/model/SiteViewModel.kt, app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt, app/src/main/java/com/jerboa/ui/components/comment/CommentNodes.kt, app/src/main/java/com/jerboa/ui/components/comment/CommentOptionsDropdown.kt, app/src/main/java/com/jerboa/ui/components/comment/mentionnode/CommentMentionNode.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityActivity.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostListing.kt, app/src/main/java/com/jerboa/ui/components/post/PostListings.kt, app/src/main/java/com/jerboa/ui/components/post/composables/PostOptionsDropdown.kt
Fix #1411 
Fix #1408 
- Fixed some admin actions being shown to non admin mods
- Did more deep research into the non admin can't ban user from community. I couldn't reproduce this at all. *User was certain though it was a community ban and not a instance ban* 
- Added a simulateModerators only for post options popup menu, it is not completely correct but this way non admin mods which probably make up most of the mods can actually moderate from the main feed. In case of the edge case moderator moderates a higher mod, the call will fail. So not that bad
- Also fixed the weird movement of the post when opening the morePostOptions menu (regression)
see https://stackoverflow.com/questions/77010371/prevent-popup-from-adding-padding-in-a-column-with-arrangement-spacedbylarge-p
=> Fix admin actions visibility for non admin mods

app/src/main/java/com/jerboa/ui/components/common/MarkdownHelper.kt, app/src/main/java/com/jerboa/ui/components/reports/ReportsActivity.kt, app/src/main/java/com/jerboa/util/markwon/ScriptRewriteSupportPlugin.kt, app/src/test/java/com/jerboa/util/markwon/ScriptRewriteSupportPluginTest.kt
=> Fix super and sub script not being properly rendered

app/build.gradle.kts, app/src/main/java/com/jerboa/ui/components/common/TimeAgo.kt, benchmarks/build.gradle.kts, build.gradle.kts
=> Remove v0.18.4 and less workaround for missing timezone in datetime

app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt, app/src/test/java/com/jerboa/UtilsKtTest.kt
=> Removing bars on non-top level comments. Fixes #1388

app/build.gradle.kts, app/src/main/java/com/jerboa/JerboaApplication.kt, app/src/main/java/com/jerboa/feat/AccountVerificationState.kt
Coil has support to show first frames of videos.
Now this doesn't work for the image viewer. Not sure why.
Also discovered that the `components` override each in the newBuilder() thing but setting it for gifImage  loader which is used by the imageviewer doesn't solve it. (Just displays black instead of failure)
Add logging for that login action, but i doubt that it errors. Else the delete action wouldn't succeed
=> Add first frame video support for comment videos

app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/ui/components/imageviewer/ImageViewerActivity.kt
Fixes #1427 
was pretty simple
=> Fix saving webm videos

app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/ui/components/community/list/CommunityListActivity.kt, app/src/main/java/com/jerboa/ui/components/home/BottomNavActivity.kt, app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt, app/src/main/java/com/jerboa/ui/components/inbox/InboxActivity.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileActivity.kt, app/src/main/java/com/jerboa/ui/components/registrationapplications/RegistrationApplicationsActivity.kt, app/src/main/java/com/jerboa/ui/components/reports/ReportsActivity.kt, app/src/main/res/values/themes.xml
I guess we didn't need edge to edge. Causes too much problems atm
Fixes #1436 
Fixes #1441 
Fixes #1439
Fixes #1437
=> Fix issues caused by edge to edge

app/schemas/com.jerboa.db.AppDB/31.json, app/src/main/java/com/jerboa/db/AppDB.kt, app/src/main/java/com/jerboa/db/AppDBMigrations.kt
This is really annoying, the order of these column definitions is very important.
This caused half the settings to be switched with two columns lower.
This fixes that
It is actually miracle that this didnt cause any crashes (well if it did we would have found it earlier). I don't see how to add a test for this to prevent this from happening again.
We will have to be very careful with doing big changes to appSettings again
Fixes #1440
I have verified this with a pre 30 db version app and  31 has the exact same settings.
=> Fix migration changing the the app settings

app/schemas/com.jerboa.db.AppDB/32.json, app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/db/AppDB.kt, app/src/main/java/com/jerboa/db/AppDBMigrations.kt, app/src/main/java/com/jerboa/db/entity/AppSettings.kt, app/src/main/java/com/jerboa/feat/SwipeToAction.kt, app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt, app/src/main/java/com/jerboa/ui/components/post/PostListing.kt, app/src/main/java/com/jerboa/ui/components/post/PostListings.kt, app/src/main/java/com/jerboa/ui/components/settings/lookandfeel/LookAndFeelActivity.kt
Okay, I strongly typed all our default values, and double checked the column order (2 were in the wrong place iirc).
It'd be good if you could test this also, just to be sure it doesn't break existing installs.
=> Fix migrations 1

app/src/main/java/com/jerboa/JerboaAppState.kt, app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/datatypes/SampleData.kt, app/src/main/java/com/jerboa/ui/components/common/AppBars.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityActivity.kt, app/src/main/java/com/jerboa/ui/components/community/sidebar/CommunitySidebar.kt, app/src/main/java/com/jerboa/ui/components/community/sidebar/CommunitySidebarActivity.kt, app/src/main/java/com/jerboa/ui/components/home/sidebar/SiteSidebar.kt, app/src/main/java/com/jerboa/ui/components/home/sidebar/SiteSidebarActivity.kt, app/src/main/res/values/strings.xml
Example:
I originally tried a `FlowRow` but it didn't look as great.
=> Add community mods and admins to sidebars. Fixes #1343

app/src/main/java/com/jerboa/ui/components/drawer/DrawerActivity.kt
=> Subscriptions list ignores case when sorting

app/build.gradle.kts, app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/datatypes/Others.kt, app/src/main/java/com/jerboa/feat/PostNavigationGestureMode.kt, app/src/main/java/com/jerboa/feat/SwipeToAction.kt, app/src/main/java/com/jerboa/ui/components/community/Community.kt, app/src/main/java/com/jerboa/ui/components/home/Home.kt, app/src/main/java/com/jerboa/ui/components/settings/SettingsActivity.kt, app/src/main/java/com/jerboa/ui/components/settings/about/AboutActivity.kt, app/src/main/java/com/jerboa/ui/components/settings/account/AccountSettings.kt, app/src/main/java/com/jerboa/ui/components/settings/lookandfeel/LookAndFeelActivity.kt, app/src/main/java/com/jerboa/ui/theme/Sizes.kt, app/src/main/res/values/strings.xml
This one turned out to be much easier to use.
=> Moving to a new preferences library.

app/src/main/java/com/jerboa/model/PostViewModel.kt, app/src/main/java/com/jerboa/ui/components/post/PostActivity.kt
When we sort the comments on the PostActivity, the post information is also fetched (instead of just the comments). This PR fixes this. 
https://github.com/dessalines/jerboa/assets/56604262/d09796f6-a7df-4522-9f95-5d9d64f31275
https://github.com/dessalines/jerboa/assets/56604262/6670a095-4a15-4523-aa9a-459758466d37
=> Prevents posts from reloading when changing the comments sorting

app/src/main/java/com/jerboa/ui/components/settings/account/AccountSettings.kt
Fixes #1461 
Verified that this causes the mail to be no longer be included in the body if its empty
=> Fix email required error when saving user settings when no email set on email required instance

app/src/main/java/com/jerboa/ui/components/common/AppBars.kt, app/src/main/java/com/jerboa/ui/components/login/Login.kt, app/src/main/java/com/jerboa/ui/components/login/LoginActivity.kt
This fixes a few other top app bar titles by using `titleSmall`
=> Fixing a few other top app bar title sizes.

app/src/main/java/com/jerboa/model/SiteViewModel.kt, app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt
=> Fix Saved comments footer empty space doesn't open post

app/src/main/java/com/jerboa/ui/components/common/VoteHelpers.kt
For #1514
> The upvote buttons are read as ‘downvoted’.
I had noticed this before but I had fixed it wrongly.
=> Fix content description for upvotes

app/benchmark-rules.pro, app/build.gradle.kts, build.gradle.kts
The 2.0.0 kotlin compiler has been released already. It just moved now to a plugin
https://developer.android.com/jetpack/androidx/releases/compose-kotlin
=> chore(deps): update kotlin monorepo to v2 (major)

app/build.gradle.kts, app/src/main/java/com/jerboa/ui/components/common/Modifiers.kt, app/src/main/java/com/jerboa/ui/components/login/Login.kt, app/src/main/java/com/jerboa/ui/components/settings/account/AccountSettings.kt
context: https://github.com/LemmyNet/jerboa/pull/1502#issuecomment-2137935525
=> Use chris banes compose-bom.

app/src/main/java/com/jerboa/model/PersonProfileViewModel.kt, app/src/main/java/com/jerboa/ui/components/common/AppBars.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityActivity.kt, app/src/main/java/com/jerboa/ui/components/home/HomeActivity.kt, app/src/main/java/com/jerboa/ui/components/inbox/InboxActivity.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostActivity.kt, app/src/main/java/com/jerboa/ui/components/post/PostListings.kt, app/src/main/java/com/jerboa/ui/components/registrationapplications/RegistrationApplications.kt, app/src/main/java/com/jerboa/ui/components/reports/ReportsActivity.kt, app/src/main/java/com/jerboa/ui/components/viewvotes/comment/CommentLikesActivity.kt, app/src/main/java/com/jerboa/ui/components/viewvotes/post/PostLikesActivity.kt
I like the API of the new one, much simpler
Fix #1533
=> Fix #1533 use M3 PullToRefresh

app/build.gradle.kts, app/src/main/java/com/jerboa/MainActivity.kt, app/src/main/java/com/jerboa/feat/PostNavigationGestureMode.kt, app/src/main/java/com/jerboa/ui/components/common/SwipeToAction.kt, app/src/main/java/com/jerboa/ui/components/common/SwipeToNavigateBack.kt, app/src/main/res/values-ar/strings.xml, app/src/main/res/values-bg/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values/strings.xml
Use M3 replacement.
Whats strange is that they named it "Swipe left" but dragging to right is swiping right? So I have corrected the naming to fit the behaviour.
This was the last accompanist dependency. Also the last M1 component.
Fixes #1479
https://github.com/LemmyNet/jerboa/assets/67873169/0a1e92d2-a1ff-4d0c-b9d7-01a4e519598d
=> Refactor deprecated M1 SwipeToDismiss, use M3 SwipeToDismissBox

app/src/main/java/com/jerboa/ui/components/post/PostListing.kt
Fixes #1547 
Stills shows description
=> Hide Metadata outline when no metadata is shown

app/src/main/java/com/jerboa/ui/components/common/TimeAgo.kt
I think the fontsize of  voting types are a bit too small. We can slightly increase it and it will still be capable of showing all the voting types. All though it will be very rare that someone has enabled all of them. I believe its better to cater to the common case which will be showing two voting types.
After: (14 SP)
Before: (12 SP)
=> Increase fontsize votes slightly

app/src/main/java/com/jerboa/model/SiteViewModel.kt, app/src/main/java/com/jerboa/ui/components/settings/account/AccountSettings.kt
This fixes the show_scores for pre 0.19.4 anon users. This maintains the previous behaviour.
=> Fix edgecase with legacy show_scores

app/build.gradle.kts
There was a bug in LemmyAPI where for the initial page_cursor it would use the page instead of the page_cursor (null).
=> Fix initial page_cursor

cliff.toml
=> Remove renovate bot from git cliff changelogs.

app/src/main/java/com/jerboa/util/markwon/MarkwonSpoilerPlugin.kt
- The spans are now overwriting the correct text even if the text has changed since the first parsing
- Fixes #1577
=> Fix multiple spoiler blocks displaying incorrectly (#1577)

app/src/main/java/com/jerboa/Constants.kt, app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/ui/components/post/PostListing.kt, app/src/main/java/com/jerboa/ui/components/post/create/CreatePostScreen.kt, app/src/main/java/com/jerboa/ui/components/settings/about/AboutScreen.kt, app/src/main/res/values/strings.xml
- Fixes URI validation to include magnet link schemes.
- When creating a post, can automatically copy the torrent title from the link.
- Adds a torrent helper for magnet links.
- Fixes magnet link clicks.
- Fixes #1609
Pics:
=> Bettering torrent support.

app/build.gradle.kts, app/src/main/java/com/jerboa/feed/FeedController.kt, app/src/main/java/com/jerboa/feed/PostController.kt, app/src/main/java/com/jerboa/feed/UniqueFeedController.kt, app/src/test/java/com/jerboa/feed/UniqueFeedControllerTest.kt
Before the FeedController we had deduplication logic. I presumed this wasn't necessary anymore with pagination cursor. But it seems that is not the case. I have added support for it.
=> Deduplicate posts in the feed

app/src/main/java/com/jerboa/ui/components/post/PostListings.kt
After a while I realized this looks better:
=> Adding post divider back.

app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/ui/components/comment/CommentNode.kt, app/src/main/java/com/jerboa/ui/components/comment/mentionnode/CommentMentionNode.kt, app/src/main/java/com/jerboa/ui/components/comment/replynode/CommentReplyNode.kt, app/src/main/java/com/jerboa/ui/components/common/AppBars.kt, app/src/main/java/com/jerboa/ui/components/common/DrawerItems.kt, app/src/main/java/com/jerboa/ui/components/common/InputFields.kt, app/src/main/java/com/jerboa/ui/components/common/MarkdownHelper.kt, app/src/main/java/com/jerboa/ui/components/common/Modifiers.kt, app/src/main/java/com/jerboa/ui/components/common/PictrsImage.kt, app/src/main/java/com/jerboa/ui/components/common/TextBadge.kt, app/src/main/java/com/jerboa/ui/components/common/TimeAgo.kt, app/src/main/java/com/jerboa/ui/components/common/VoteHelpers.kt, app/src/main/java/com/jerboa/ui/components/community/Community.kt, app/src/main/java/com/jerboa/ui/components/community/CommunityLink.kt, app/src/main/java/com/jerboa/ui/components/drawer/Drawer.kt, app/src/main/java/com/jerboa/ui/components/home/legal/SiteLegalScreen.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfile.kt, app/src/main/java/com/jerboa/ui/components/person/PersonProfileLink.kt, app/src/main/java/com/jerboa/ui/components/post/PostListing.kt, app/src/main/java/com/jerboa/ui/components/post/composables/PostComposables.kt, app/src/main/java/com/jerboa/ui/components/privatemessage/PrivateMessage.kt, app/src/main/java/com/jerboa/ui/components/settings/account/AccountSettings.kt, app/src/main/java/com/jerboa/ui/theme/Color.kt
- Adding a fade to the post body preview.
- Getting rid of muted, using colorScheme.outlined instead.
- Making label-type text use label rather than body style.
- Getting rid of some unecessary surface and onSurface colors.
- Fixes #1608
Example:
=> Some material 3 cleanups.

app/src/main/java/com/jerboa/ui/components/common/AppBars.kt, app/src/main/java/com/jerboa/ui/theme/Theme.kt
The statusbar is not as perfect as before as it would change with the elevation color change, now not anymore.
These changes are needed:
```
insets.isAppearanceLightStatusBars = isLight
insets.isAppearanceLightNavigationBars = isLight
```
This is needed so that if you don't have system set as ThemeMode it will still set the correct (inverse) coloring of the statusbar.    
```
window.statusBarColor = Color.Transparent.toArgb()
```
Needed to mimic translucentStatus. Not as good but pretty close. see #1607 removal
The navigationbar seemed to use a different container color now. So this solves that.
#1649
=> Fixes mostly systembars colors not matching with application

app/build.gradle.kts, app/src/main/java/com/jerboa/ui/components/common/AppBars.kt
Since we switched to edgeToEdge. The height now starts from the bottom. (Before the System navigation bar instead of after) This small tweak makes it apply like before.
Fixes #1648
=> Fixes wrong height Navigation bar when descriptions where hidden.

app/src/main/java/com/jerboa/feat/Voting.kt, app/src/main/java/com/jerboa/model/SiteViewModel.kt, app/src/main/java/com/jerboa/ui/components/common/VoteHelpers.kt
Fixes #1626
I map the legacy behaviour into the new viewMode makes it much easier to reason about. And we can remove the legacy checks.
=> Fix legacy score behaviour

app/src/main/java/com/jerboa/ui/components/common/SwipeToNavigateBack.kt
Fixes #1653 
This was wrongly implemented, they hooked into the confirmation callback but this fires multiple times.
I used the actual state now.
=> Fix 'Swipe right to navigate back' to go back multiple times

renovate.json
Renovate rate limits itself, so it couldn't always finish up the rest of the updates. This gives it a larger window, without spamming notifications during the week.
=> Running renovate every weekend.

app/src/main/java/com/jerboa/Utils.kt, app/src/test/java/com/jerboa/UtilsKtTest.kt
The `padUrlWithHttps` function broke magnet link posts.
=> Fixing bug with torrent magnet link posts.

app/src/main/java/com/jerboa/Utils.kt, benchmarks/build.gradle.kts
Worked on API Level 28 and below, uses a different API.
It fails to read MIME type from url. Normally thats fine, it will infer later when it gets inserted. For most images that okay, but it seems for webp images (or atleast those from pictrs) it infers the mime as "application/octet-stream" and then it throws exception because `Images.Media.EXTERNAL_CONTENT_URI` doesn't allow that MIME to be inserted there.
I looked at what some other clients do, some dont set MIME at all, meaning those images would also fail. Some always set `image/jpeg`. I added fallback for that here.
Not sure what the future holds for image_proxy endpoint? If kept we might want to better support it, properly extract extension and filename from it.
Fixes #1800 
allDevices was fix for deprecation (just rename)
---
This …
=> Fixes: Webp images using image_proxy can't be saved in Android 10+

.woodpecker.yml, RESOURCES.md, app/build.gradle.kts, app/src/debug/res/values-ru/strings.xml, app/src/main/AndroidManifest.xml, app/src/main/java/com/jerboa/Utils.kt, app/src/main/java/com/jerboa/ui/components/comment/CommentOptionsDropdown.kt, app/src/main/java/com/jerboa/ui/components/comment/mentionnode/CommentMentionOptionsDropdown.kt, app/src/main/java/com/jerboa/ui/components/comment/replynode/CommentReplyOptionsDropdown.kt, app/src/main/java/com/jerboa/ui/components/common/LinkDropDownMenu.kt, app/src/main/java/com/jerboa/ui/components/common/Modifiers.kt, app/src/main/java/com/jerboa/ui/components/login/Login.kt, app/src/main/java/com/jerboa/ui/components/post/composables/PostOptionsDropdown.kt, app/src/main/java/com/jerboa/ui/components/settings/about/AboutScreen.kt, app/src/main/java/com/jerboa/util/BlurTransformation.kt, app/src/main/java/com/jerboa/util/markwon/ClickableCoilImagesPlugin.kt, app/src/main/res/values-bg/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values-zh/strings.xml, app/src/main/res/xml/locales_config.xml, build.gradle.kts
Discovered Android Lint recently, Its pretty handy. I discovered some issues with the translations with it. I have added it to the CI.
It generates a report like this.
Also bump SDK to 35 and Compose Bom to 2025.05
Fixes LocalClipboardManager deprecations (new API)
Fixes autofill deprecations (new API)
the setColor for statusBar and navigationBar have been deprecated because in Android 15. Its fixed to some transparent mode.
So not sure yet how to handle this for pre android 15. Will check that out later.
=> Add Android 15 SDK support, Configure Android lint, deprecation fixes

app/src/main/java/com/jerboa/model/CommentReplyViewModel.kt, app/src/main/java/com/jerboa/model/PrivateMessageReplyViewModel.kt, app/src/main/java/com/jerboa/ui/components/comment/reply/CommentReplyScreen.kt, app/src/main/java/com/jerboa/ui/components/common/InputFields.kt, app/src/main/java/com/jerboa/ui/components/privatemessage/PrivateMessageReplyScreen.kt
When sending the comment, it goes into "loading" mode, here the CommentReplyView leaves the composition, then when it receives response it goes into ApiState Success. Now the previous ReplyView enters composition again for short period. Where it asks for focus again. Thus the open keyboard state after creating a comment.
This fixes it by not showing the CommentReply view after sending. Thus it doesnt ask for focus.
Also removed the focus removal. It doesn't seem to do anything.
https://github.com/user-attachments/assets/345e0554-3d78-4007-aed0-fff8438af54f
The other screens aren't affected because they don't show a loading bar and hide the body. Thus it doesn't leave composition. :)
Fixes #1755
=> Fixes #1755 Keyboard still open after creating comment

app/src/main/java/com/jerboa/feat/UserActions.kt
A failure like this below in `saveMedia` action would cause the app to crash. Due to missing catch. I checked some other actions they seem good.
> java.lang.IllegalStateException: Failed to build unique file: /storage/emulated/0/Pictures/Jerboa image_proxy
Now the failure itself. Apparently you can only have like 32 duplicate filenames before it starts throwing that failure. For 
See screenshots below (This could be selective to only a few Android versions)
This was found because it would save all image_proxy images as "image_proxy" likely would not have been encountered else. But if we do seem to be encountering this elseware and it not being a specific android version specific. We could look into preventing this failure. (Randomized hash as filename or looking up how some other apps …
=> Fix edgecase saveImage failing causing crash

app/proguard-rules.pro
From https://issuetracker.google.com/issues/425120571
It seems they forgot to readd a proguard rule.
This should fix the crashes on Android 9
Fixes #1849
=> Fix crashes on Android 9 due to compose bump

app/build.gradle.kts
I did some testing and reading, by default R8 isn't on. Unless you specify `isMinifyEnabled `
see https://developer.android.com/topic/performance/app-optimization/enable-app-optimization
APK results
```
-rwxrwxrwx 1 maart maart 5.7M Sep 17 20:07 app-release-full-optimize.apk
-rwxrwxrwx 1 maart maart  23M Sep 17 20:08 app-release-no-optimize-stuff.apk
-rwxrwxrwx 1 maart maart 5.9M Sep 17 20:13 app-release-old-processing.apk
-rwxrwxrwx 1 maart maart 7.5M Sep 17 20:25 app-release-r8-standard.apk
```
Full optimize with r8 , gives the smallest apk but destroys stracktrace debug information. This info is crucial.
(enabled with)
```
isMinifyEnabled = true
isShrinkResources = true
proguardFiles(
getDefaultProguardFile("proguard-android-optimize.txt"),
"proguard-rules.pro"
)
```
see 
So I have …
=> Restore deprecated apk post processing config
